// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ3E7m4c-Uo7me-wdoo5paWlrjQz4TJ5Q',
    appId: '1:920507793853:web:6eda6f92aa654f2a8692d4',
    messagingSenderId: '920507793853',
    projectId: 'nakamatest-aab69',
    authDomain: 'nakamatest-aab69.firebaseapp.com',
    storageBucket: 'nakamatest-aab69.firebasestorage.app',
    measurementId: 'G-2J6M1VK806',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9-E865M32Myo4U_jfijevY19bA-d8vt0',
    appId: '1:920507793853:android:67592c39502e101b8692d4',
    messagingSenderId: '920507793853',
    projectId: 'nakamatest-aab69',
    storageBucket: 'nakamatest-aab69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGYcD3aailE62KsPMOi8kWbCq5yDUBYhs',
    appId: '1:920507793853:ios:1c998e97e6db775c8692d4',
    messagingSenderId: '920507793853',
    projectId: 'nakamatest-aab69',
    storageBucket: 'nakamatest-aab69.firebasestorage.app',
    iosBundleId: 'com.example.nakamatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGYcD3aailE62KsPMOi8kWbCq5yDUBYhs',
    appId: '1:920507793853:ios:1c998e97e6db775c8692d4',
    messagingSenderId: '920507793853',
    projectId: 'nakamatest-aab69',
    storageBucket: 'nakamatest-aab69.firebasestorage.app',
    iosBundleId: 'com.example.nakamatest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ3E7m4c-Uo7me-wdoo5paWlrjQz4TJ5Q',
    appId: '1:920507793853:web:677e3ac28c1eca1d8692d4',
    messagingSenderId: '920507793853',
    projectId: 'nakamatest-aab69',
    authDomain: 'nakamatest-aab69.firebaseapp.com',
    storageBucket: 'nakamatest-aab69.firebasestorage.app',
    measurementId: 'G-709CKC4D3C',
  );
}
